### ISSUE TITLE
Example crashed at start up

### ISSUE THREAD

**Issue by dmiranda2791** [rainbow-me/react-native-animated-charts#9]
When I run the Example app on ios or android emulator I get this error:

```
error: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `../src/index.js`: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/danielmiranda/dev/libs/react-native-animated-charts/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

I have tried the 4 steps on the message without luck:

 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

I have also `yarn add @babel/runtime` but it does not seem to work. 

Thanks for the time.

**Comment by ralvescosta** [comment]
It's probably because you didn't install it as base library dependencies.

In the root folder run `yarn install` and in the Example folder run `yarn install` too.

**Comment by osdnk** [comment]
yes, exactly, @ralvescosta!

Thanks!

**Comment by dmiranda2791** [comment]
Makes sense! thanks @ralvescosta
